name: Expenza
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  flutter_svg: ^2.3.0
  flutter_screenutil: ^5.9.3
  adaptive_platform_ui: ^0.1.107
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adaptive_will_pop_scope: ^1.0.4
  firebase_core: ^4.11.0
  cloud_firestore: ^6.6.0
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/expenza_logo.png"
  #remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/bold/
    - assets/icons/bulk/
    - assets/blue_blur.png

  fonts:
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/GoogleSansFlex-VariableFont.ttf