// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1vaY2BRuYiPV5ySw7oJV-GaJ0JFlTOF0',
    appId: '1:963229925830:web:a2497574aa8336fd9872c7',
    messagingSenderId: '963229925830',
    projectId: 'expenza-mobile',
    authDomain: 'expenza-mobile.firebaseapp.com',
    storageBucket: 'expenza-mobile.firebasestorage.app',
    measurementId: 'G-JF8LPLS6L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5eNZ5mMMVvYalUaEAFkoivSv1vLao8l4',
    appId: '1:963229925830:android:3e4e927991df98099872c7',
    messagingSenderId: '963229925830',
    projectId: 'expenza-mobile',
    storageBucket: 'expenza-mobile.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVbDcJEliapGJBeLeemQNqcv5U9pK0zw',
    appId: '1:963229925830:ios:4a2990c1387172789872c7',
    messagingSenderId: '963229925830',
    projectId: 'expenza-mobile',
    storageBucket: 'expenza-mobile.firebasestorage.app',
    androidClientId: '963229925830-1ajl1ar0o9ggktrtm8oul6emh0h9t9ap.apps.googleusercontent.com',
    iosClientId: '963229925830-2sj7tv7qv946nmkld15g46dvb4livob2.apps.googleusercontent.com',
    iosBundleId: 'com.zero.expenza.expenza',
  );
}
